### ISSUE TITLE
Add pyarrow 14.0.1

### ISSUE THREAD

**Issue by rasyidstat** [drivendataorg/water-supply-forecast-rodeo-runtime#15]
Hi @jayqi, could you please add pyarrow 14.0.1 to the runtime?
Thanks

**Comment by jayqi** [comment]
@rasyidstat Due to subdependency conflicts, I have added pyarrow v12.0.1 instead of v14.0.1. If you specifically need v14.0.1, then let me know and we can try to work out the conflicts with other dependencies. 

https://github.com/drivendataorg/water-supply-forecast-rodeo-runtime/commit/2754072b934694f47510f0697a2af97c1afe5c10
